version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run: sudo apt-get install default-jre
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
      - checkout
      - node/with-cache:
          steps:
            - run: cd selenium-webdriver-mocha && npm install
            - run:
                command: cd selenium-webdriver-mocha && ls && cat package.json
            - run: cd selenium-webdriver-mocha && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
