version: 2
jobs:
  build:
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Download Chrome
          command: curl -O https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F770581%2Fchrome-linux.zip?generation=1589986122953922&alt=media
      - run:
          name: Download Chromedriver
          command: curl -O https://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          command: cd selenium-webdriver-mocha && npm install && npm test
