version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    docker:
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd selenium-webdriver-mocha && npm install
            - run:
                command: cd selenium-webdriver-mocha && ls && cat package.json
            - run: cd selenium-webdriver-mocha && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
