version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
      - image: selenium/standalone-chrome:3.5.0
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          command: cd selenium-webdriver-mocha && npm install && npm test
