version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd selenium-webdriver-mocha && npm install
            - run:
                command: ls && cat README.md
            - run: cd selenium-webdriver-mocha && npm run test:allure
workflows:
    build-and-test:
      jobs:
        - build-and-test
